// ─── Types ────────────────────────────────────────────────────────────────────

export type Currency = "INR" | "USD" | "EUR" | "GBP";
export type BillingCycle = "monthly" | "yearly";

export interface PricingTier {
    name: string;
    monthlyPrice: string;
    yearlyPrice: string;
    description: string;
    features: string[];
    cta: string;
    ctaLink: string;
    highlight?: boolean;
    highlightText?: string;
    /** Short competitive note shown on the homepage pricing section */
    gainsightNote?: string;
}

// ─── Plan Data ────────────────────────────────────────────────────────────────

export const PRICING_DATA: Record<Currency, PricingTier[]> = {
    INR: [
        {
            name: "Free",
            monthlyPrice: "₹0",
            yearlyPrice: "₹0",
            description: "Perfect for individuals just starting out",
            features: [
                "25 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Objection Handling",
                "CRM Integration",
                "Advanced Follow-Ups",
                "Executive Summaries",
                "Reporting Dashboard",
                "Dedicated Success Manager",
                "Priority Slack Support",
                "API Access",
                "Onboarding Consultation",
            ],
            cta: "Start for Free",
            ctaLink: "/contact",
            gainsightNote: "No credit card required",
        },
        {
            name: "Starter",
            monthlyPrice: "₹49,000",
            yearlyPrice: "₹39,000",
            description: "For small teams scaling up",
            features: [
                "200 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Basic Objection Handling",
                "HubSpot CRM Integration",
                "Weekly Executive Summaries",
            ],
            cta: "Get Started",
            ctaLink: "/contact",
            gainsightNote: "Traditional enterprise tools start at ₹25,00,000/year",
        },
        {
            name: "Growth",
            monthlyPrice: "₹99,000",
            yearlyPrice: "₹79,000",
            description: "For growing companies",
            features: [
                "1,000 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Smart AI Objection Handling",
                "HubSpot + 1 CRM Integration",
                "Advanced Follow-Ups",
                "Advanced Executive Summaries",
                "Reporting Dashboard",
                "Onboarding Consultation",
            ],
            cta: "Get Started",
            ctaLink: "/contact",
            highlight: true,
            highlightText: "Most Popular",
            gainsightNote: "Enterprise equivalent: ₹6–10L/month",
        },
        {
            name: "Scale",
            monthlyPrice: "₹1,79,000",
            yearlyPrice: "₹1,49,000",
            description: "For large enterprises",
            features: [
                "Unlimited Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Smart AI Objection Handling",
                "Multi-CRM Integration",
                "Advanced Follow-Ups",
                "Custom Executive Summaries",
                "Custom Reporting Dashboard",
                "Dedicated Success Manager",
                "Priority Slack Support",
                "API Access",
                "Onboarding Consultation",
            ],
            cta: "Contact Sales",
            ctaLink: "/contact",
            gainsightNote: "Enterprise-grade features at a fraction of the cost",
        },
    ],

    USD: [
        {
            name: "Free",
            monthlyPrice: "$0",
            yearlyPrice: "$0",
            description: "Perfect for individuals just starting out",
            features: [
                "25 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Objection Handling",
                "CRM Integration",
                "Advanced Follow-Ups",
                "Executive Summaries",
                "Reporting Dashboard",
                "Dedicated Success Manager",
                "Priority Slack Support",
                "API Access",
                "Onboarding Consultation",
            ],
            cta: "Start for Free",
            ctaLink: "/contact",
            gainsightNote: "No credit card required",
        },
        {
            name: "Starter",
            monthlyPrice: "$499",
            yearlyPrice: "$399",
            description: "For small teams scaling up",
            features: [
                "200 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Basic Objection Handling",
                "HubSpot CRM Integration",
                "Weekly Executive Summaries",
            ],
            cta: "Get Started",
            ctaLink: "/contact",
            gainsightNote: "Traditional enterprise tools start at $30,000/year",
        },
        {
            name: "Growth",
            monthlyPrice: "$999",
            yearlyPrice: "$799",
            description: "For growing companies",
            features: [
                "1,000 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Smart AI Objection Handling",
                "HubSpot + 1 CRM Integration",
                "Advanced Follow-Ups",
                "Advanced Executive Summaries",
                "Reporting Dashboard",
                "Onboarding Consultation",
            ],
            cta: "Get Started",
            ctaLink: "/contact",
            highlight: true,
            highlightText: "Most Popular",
            gainsightNote: "Enterprise equivalent: $8,000–$12,000/month",
        },
        {
            name: "Scale",
            monthlyPrice: "$1,799",
            yearlyPrice: "$1,499",
            description: "For large enterprises",
            features: [
                "Unlimited Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Smart AI Objection Handling",
                "Multi-CRM Integration",
                "Advanced Follow-Ups",
                "Custom Executive Summaries",
                "Custom Reporting Dashboard",
                "Dedicated Success Manager",
                "Priority Slack Support",
                "API Access",
                "Onboarding Consultation",
            ],
            cta: "Contact Sales",
            ctaLink: "/contact",
            gainsightNote: "Enterprise-grade features at a fraction of the cost",
        },
    ],

    EUR: [
        {
            name: "Free",
            monthlyPrice: "€0",
            yearlyPrice: "€0",
            description: "Perfect for individuals just starting out",
            features: [
                "25 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Objection Handling",
                "CRM Integration",
                "Advanced Follow-Ups",
                "Executive Summaries",
                "Reporting Dashboard",
                "Dedicated Success Manager",
                "Priority Slack Support",
                "API Access",
                "Onboarding Consultation",
            ],
            cta: "Start for Free",
            ctaLink: "/contact",
            gainsightNote: "No credit card required",
        },
        {
            name: "Starter",
            monthlyPrice: "€449",
            yearlyPrice: "€359",
            description: "For small teams scaling up",
            features: [
                "200 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Basic Objection Handling",
                "HubSpot CRM Integration",
                "Weekly Executive Summaries",
            ],
            cta: "Get Started",
            ctaLink: "/contact",
            gainsightNote: "Traditional enterprise tools start at €28,000/year",
        },
        {
            name: "Growth",
            monthlyPrice: "€899",
            yearlyPrice: "€719",
            description: "For growing companies",
            features: [
                "1,000 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Smart AI Objection Handling",
                "HubSpot + 1 CRM Integration",
                "Advanced Follow-Ups",
                "Advanced Executive Summaries",
                "Reporting Dashboard",
                "Onboarding Consultation",
            ],
            cta: "Get Started",
            ctaLink: "/contact",
            highlight: true,
            highlightText: "Most Popular",
            gainsightNote: "Enterprise equivalent: €7,000–€11,000/month",
        },
        {
            name: "Scale",
            monthlyPrice: "€1,599",
            yearlyPrice: "€1,279",
            description: "For large enterprises",
            features: [
                "Unlimited Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Smart AI Objection Handling",
                "Multi-CRM Integration",
                "Advanced Follow-Ups",
                "Custom Executive Summaries",
                "Custom Reporting Dashboard",
                "Dedicated Success Manager",
                "Priority Slack Support",
                "API Access",
                "Onboarding Consultation",
            ],
            cta: "Contact Sales",
            ctaLink: "/contact",
            gainsightNote: "Enterprise-grade features at a fraction of the cost",
        },
    ],

    GBP: [
        {
            name: "Free",
            monthlyPrice: "£0",
            yearlyPrice: "£0",
            description: "Perfect for individuals just starting out",
            features: [
                "25 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Objection Handling",
                "CRM Integration",
                "Advanced Follow-Ups",
                "Executive Summaries",
                "Reporting Dashboard",
                "Dedicated Success Manager",
                "Priority Slack Support",
                "API Access",
                "Onboarding Consultation",
            ],
            cta: "Start for Free",
            ctaLink: "/contact",
            gainsightNote: "No credit card required",
        },
        {
            name: "Starter",
            monthlyPrice: "£399",
            yearlyPrice: "£319",
            description: "For small teams scaling up",
            features: [
                "200 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Basic Objection Handling",
                "HubSpot CRM Integration",
                "Weekly Executive Summaries",
            ],
            cta: "Get Started",
            ctaLink: "/contact",
            gainsightNote: "Traditional enterprise tools start at £25,000/year",
        },
        {
            name: "Growth",
            monthlyPrice: "£799",
            yearlyPrice: "£639",
            description: "For growing companies",
            features: [
                "1,000 Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Smart AI Objection Handling",
                "HubSpot + 1 CRM Integration",
                "Advanced Follow-Ups",
                "Advanced Executive Summaries",
                "Reporting Dashboard",
                "Onboarding Consultation",
            ],
            cta: "Get Started",
            ctaLink: "/contact",
            highlight: true,
            highlightText: "Most Popular",
            gainsightNote: "Enterprise equivalent: £7,000–£10,000/month",
        },
        {
            name: "Scale",
            monthlyPrice: "£1,499",
            yearlyPrice: "£1,199",
            description: "For large enterprises",
            features: [
                "Unlimited Active Accounts",
                "AI Renewal Sequences",
                "Email Approval Workflow",
                "Smart AI Objection Handling",
                "Multi-CRM Integration",
                "Advanced Follow-Ups",
                "Custom Executive Summaries",
                "Custom Reporting Dashboard",
                "Dedicated Success Manager",
                "Priority Slack Support",
                "API Access",
                "Onboarding Consultation",
            ],
            cta: "Contact Sales",
            ctaLink: "/contact",
            gainsightNote: "Enterprise-grade features at a fraction of the cost",
        },
    ],
};

// ─── Add-ons ──────────────────────────────────────────────────────────────────

export const ADD_ONS: Record<Currency, string> = {
    INR: "₹35,000 / month",
    USD: "$349 / month",
    EUR: "€299 / month",
    GBP: "£299 / month",
};

// ─── Currency symbols (for display) ──────────────────────────────────────────

export const CURRENCY_LABELS: Record<Currency, string> = {
    INR: "₹ INR",
    USD: "$ USD",
    EUR: "€ EUR",
    GBP: "£ GBP",
};