// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: form_submission.
// - Entity ID: 102019b3769bd577f27bc355a97b2d5c09c.
// - Entity Version: 102019b3b6ac4557b898ad7a712947f55d3.
// - Task ID: 6946818aa5628caec8233fc1.
// - Task Root ID: 69457ad84618447456c9af69.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for FormSubmissionFormType
 */
export enum FormSubmissionFormType {
  Unspecified = 0,
  demo_request = 1,
  general_contact = 2,
}



/**
 * Interface for FormSubmissionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface FormSubmissionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  company_name: string;
  contact_person_name: string;
  email_address: string;
  phone_number?: string | null;
  message?: string | null;
  form_type: FormSubmissionFormType;
  submitted_at: string;
}

/**
 * ORM class for FormSubmission entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class FormSubmissionORM {
  private static instance: FormSubmissionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b3769bd577f27bc355a97b2d5c09c';
    this.entityName = 'form_submission';
    this.entityVersion = '102019b3b6ac4557b898ad7a712947f55d3';
    this.taskId = '6946818aa5628caec8233fc1';
    this.taskRootId = '69457ad84618447456c9af69';
  }

  /**
   * Get singleton instance of FormSubmissionORM
   */
  public static getInstance(): FormSubmissionORM {
    if (!FormSubmissionORM.instance) {
      FormSubmissionORM.instance = new FormSubmissionORM();
    }
    
    return FormSubmissionORM.instance;
  }

  /**
   * Get form_submission by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getFormSubmissionByIDs(ids: string[]): Promise<FormSubmissionModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete form_submission by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteFormSubmissionByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all FormSubmission records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllFormSubmission(): Promise<FormSubmissionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new FormSubmission record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertFormSubmission(data: FormSubmissionModel[]): Promise<FormSubmissionModel[]> {
    const structured = data.map((item) => CreateData(FormSubmissionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all FormSubmission records
   */
  async purgeAllFormSubmission(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List FormSubmission records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listFormSubmission(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[FormSubmissionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get form_submission by Id index
   * This function gets data by index.
   */
  async getFormSubmissionById(
    id: string,
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) form_submission by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFormSubmissionById(
    id: string,
    data: FormSubmissionModel
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexId(
      id
    );

    const values = FormSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete form_submission by Id index
   */
  async deleteFormSubmissionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get form_submission by DataCreator index
   * This function gets data by index.
   */
  async getFormSubmissionByDataCreator(
    data_creator: string,
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) form_submission by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFormSubmissionByDataCreator(
    data_creator: string,
    data: FormSubmissionModel
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = FormSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete form_submission by DataCreator index
   */
  async deleteFormSubmissionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get form_submission by DataUpdater index
   * This function gets data by index.
   */
  async getFormSubmissionByDataUpdater(
    data_updater: string,
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) form_submission by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFormSubmissionByDataUpdater(
    data_updater: string,
    data: FormSubmissionModel
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = FormSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete form_submission by DataUpdater index
   */
  async deleteFormSubmissionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get form_submission by FormType index
   * This function gets data by index.
   */
  async getFormSubmissionByFormType(
    form_type: FormSubmissionFormType,
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexFormType(
      form_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) form_submission by FormType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFormSubmissionByFormType(
    form_type: FormSubmissionFormType,
    data: FormSubmissionModel
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexFormType(
      form_type
    );

    const values = FormSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete form_submission by FormType index
   */
  async deleteFormSubmissionByFormType(
    form_type: FormSubmissionFormType
  ): Promise<void> {
    const index = createIndexFormType(
      form_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get form_submission by SubmittedAt index
   * This function gets data by index.
   */
  async getFormSubmissionBySubmittedAt(
    submitted_at: string,
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexSubmittedAt(
      submitted_at
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) form_submission by SubmittedAt index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFormSubmissionBySubmittedAt(
    submitted_at: string,
    data: FormSubmissionModel
  ): Promise<FormSubmissionModel[]> {
    const index = createIndexSubmittedAt(
      submitted_at
    );

    const values = FormSubmissionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete form_submission by SubmittedAt index
   */
  async deleteFormSubmissionBySubmittedAt(
    submitted_at: string
  ): Promise<void> {
    const index = createIndexSubmittedAt(
      submitted_at
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to FormSubmissionModel data array
   */
  private resultToData(values: Data[]): FormSubmissionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return FormSubmissionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as FormSubmissionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized FormSubmissionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is FormSubmissionModel => item !== null);
  }
}

/**
 * Convert FormSubmissionModel data to Value array
 */
function FormSubmissionModelToValues(data: FormSubmissionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'company_name', type: DataType.string, defaultValue: '' },
    { key: 'contact_person_name', type: DataType.string, defaultValue: '' },
    { key: 'email_address', type: DataType.string, defaultValue: '' },
    { key: 'phone_number', type: DataType.string, defaultValue: null },
    { key: 'message', type: DataType.string, defaultValue: null },
    { key: 'form_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'submitted_at', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof FormSubmissionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to FormSubmissionModel data
 */
function FormSubmissionModelFromValues(values: Value[]): FormSubmissionModel {
  const data: Partial<FormSubmissionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'company_name':
        data.company_name = ParseValue(value, DataType.string) as string;
        break;
      case 'contact_person_name':
        data.contact_person_name = ParseValue(value, DataType.string) as string;
        break;
      case 'email_address':
        data.email_address = ParseValue(value, DataType.string) as string;
        break;
      case 'phone_number':
        data.phone_number = ParseValue(value, DataType.string) as string | null;
        break;
      case 'message':
        data.message = ParseValue(value, DataType.string) as string | null;
        break;
      case 'form_type':
        data.form_type = ParseValue(value, DataType.enumeration) as FormSubmissionFormType;
        break;
      case 'submitted_at':
        data.submitted_at = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as FormSubmissionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for FormType fields
 */
function createIndexFormType(
  form_type: FormSubmissionFormType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, form_type, 'form_type'),
  ];

  return {
    fields: ['form_type'],
    values
  };
}
/**
 * Create index for SubmittedAt fields
 */
function createIndexSubmittedAt(
  submitted_at: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, submitted_at, 'submitted_at'),
  ];

  return {
    fields: ['submitted_at'],
    values
  };
}

export default FormSubmissionORM;