/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GlimpsesRouteImport } from './routes/glimpses'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as BlogZendeskHubspotSalesforceCsPlatformComparisonRouteImport } from './routes/blog/zendesk-hubspot-salesforce-cs-platform-comparison'
import { Route as BlogWhySaasCompaniesLoseRenewalsRouteImport } from './routes/blog/why-saas-companies-lose-renewals'
import { Route as BlogWhatIsRenewalAutomationRouteImport } from './routes/blog/what-is-renewal-automation'
import { Route as BlogTotangoAlternativeFasterRenewalAutomationRouteImport } from './routes/blog/totango-alternative-faster-renewal-automation'
import { Route as BlogHowToRunYourEntireCsOperationInRenewal360RouteImport } from './routes/blog/how-to-run-your-entire-cs-operation-in-renewal360'
import { Route as BlogHowToAutomateSaasRenewalEmailsRouteImport } from './routes/blog/how-to-automate-saas-renewal-emails'
import { Route as BlogHowRenewal360WorksRouteImport } from './routes/blog/how-renewal360-works'
import { Route as BlogGainsightVsTotangoVsRenewal360RouteImport } from './routes/blog/gainsight-vs-totango-vs-renewal360'
import { Route as BlogCustomerSuccessPlatformForGrowingSaasRouteImport } from './routes/blog/customer-success-platform-for-growing-saas'
import { Route as BlogChurnzeroAlternativeGrowingSaasTeamsRouteImport } from './routes/blog/churnzero-alternative-growing-saas-teams'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GlimpsesRoute = GlimpsesRouteImport.update({
  id: '/glimpses',
  path: '/glimpses',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogZendeskHubspotSalesforceCsPlatformComparisonRoute =
  BlogZendeskHubspotSalesforceCsPlatformComparisonRouteImport.update({
    id: '/zendesk-hubspot-salesforce-cs-platform-comparison',
    path: '/zendesk-hubspot-salesforce-cs-platform-comparison',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogWhySaasCompaniesLoseRenewalsRoute =
  BlogWhySaasCompaniesLoseRenewalsRouteImport.update({
    id: '/why-saas-companies-lose-renewals',
    path: '/why-saas-companies-lose-renewals',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogWhatIsRenewalAutomationRoute =
  BlogWhatIsRenewalAutomationRouteImport.update({
    id: '/what-is-renewal-automation',
    path: '/what-is-renewal-automation',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTotangoAlternativeFasterRenewalAutomationRoute =
  BlogTotangoAlternativeFasterRenewalAutomationRouteImport.update({
    id: '/totango-alternative-faster-renewal-automation',
    path: '/totango-alternative-faster-renewal-automation',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogHowToRunYourEntireCsOperationInRenewal360Route =
  BlogHowToRunYourEntireCsOperationInRenewal360RouteImport.update({
    id: '/how-to-run-your-entire-cs-operation-in-renewal360',
    path: '/how-to-run-your-entire-cs-operation-in-renewal360',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogHowToAutomateSaasRenewalEmailsRoute =
  BlogHowToAutomateSaasRenewalEmailsRouteImport.update({
    id: '/how-to-automate-saas-renewal-emails',
    path: '/how-to-automate-saas-renewal-emails',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogHowRenewal360WorksRoute = BlogHowRenewal360WorksRouteImport.update({
  id: '/how-renewal360-works',
  path: '/how-renewal360-works',
  getParentRoute: () => BlogRoute,
} as any)
const BlogGainsightVsTotangoVsRenewal360Route =
  BlogGainsightVsTotangoVsRenewal360RouteImport.update({
    id: '/gainsight-vs-totango-vs-renewal360',
    path: '/gainsight-vs-totango-vs-renewal360',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogCustomerSuccessPlatformForGrowingSaasRoute =
  BlogCustomerSuccessPlatformForGrowingSaasRouteImport.update({
    id: '/customer-success-platform-for-growing-saas',
    path: '/customer-success-platform-for-growing-saas',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogChurnzeroAlternativeGrowingSaasTeamsRoute =
  BlogChurnzeroAlternativeGrowingSaasTeamsRouteImport.update({
    id: '/churnzero-alternative-growing-saas-teams',
    path: '/churnzero-alternative-growing-saas-teams',
    getParentRoute: () => BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/glimpses': typeof GlimpsesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/set-password': typeof SetPasswordRoute
  '/terms': typeof TermsRoute
  '/blog/churnzero-alternative-growing-saas-teams': typeof BlogChurnzeroAlternativeGrowingSaasTeamsRoute
  '/blog/customer-success-platform-for-growing-saas': typeof BlogCustomerSuccessPlatformForGrowingSaasRoute
  '/blog/gainsight-vs-totango-vs-renewal360': typeof BlogGainsightVsTotangoVsRenewal360Route
  '/blog/how-renewal360-works': typeof BlogHowRenewal360WorksRoute
  '/blog/how-to-automate-saas-renewal-emails': typeof BlogHowToAutomateSaasRenewalEmailsRoute
  '/blog/how-to-run-your-entire-cs-operation-in-renewal360': typeof BlogHowToRunYourEntireCsOperationInRenewal360Route
  '/blog/totango-alternative-faster-renewal-automation': typeof BlogTotangoAlternativeFasterRenewalAutomationRoute
  '/blog/what-is-renewal-automation': typeof BlogWhatIsRenewalAutomationRoute
  '/blog/why-saas-companies-lose-renewals': typeof BlogWhySaasCompaniesLoseRenewalsRoute
  '/blog/zendesk-hubspot-salesforce-cs-platform-comparison': typeof BlogZendeskHubspotSalesforceCsPlatformComparisonRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/glimpses': typeof GlimpsesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/set-password': typeof SetPasswordRoute
  '/terms': typeof TermsRoute
  '/blog/churnzero-alternative-growing-saas-teams': typeof BlogChurnzeroAlternativeGrowingSaasTeamsRoute
  '/blog/customer-success-platform-for-growing-saas': typeof BlogCustomerSuccessPlatformForGrowingSaasRoute
  '/blog/gainsight-vs-totango-vs-renewal360': typeof BlogGainsightVsTotangoVsRenewal360Route
  '/blog/how-renewal360-works': typeof BlogHowRenewal360WorksRoute
  '/blog/how-to-automate-saas-renewal-emails': typeof BlogHowToAutomateSaasRenewalEmailsRoute
  '/blog/how-to-run-your-entire-cs-operation-in-renewal360': typeof BlogHowToRunYourEntireCsOperationInRenewal360Route
  '/blog/totango-alternative-faster-renewal-automation': typeof BlogTotangoAlternativeFasterRenewalAutomationRoute
  '/blog/what-is-renewal-automation': typeof BlogWhatIsRenewalAutomationRoute
  '/blog/why-saas-companies-lose-renewals': typeof BlogWhySaasCompaniesLoseRenewalsRoute
  '/blog/zendesk-hubspot-salesforce-cs-platform-comparison': typeof BlogZendeskHubspotSalesforceCsPlatformComparisonRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/glimpses': typeof GlimpsesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/set-password': typeof SetPasswordRoute
  '/terms': typeof TermsRoute
  '/blog/churnzero-alternative-growing-saas-teams': typeof BlogChurnzeroAlternativeGrowingSaasTeamsRoute
  '/blog/customer-success-platform-for-growing-saas': typeof BlogCustomerSuccessPlatformForGrowingSaasRoute
  '/blog/gainsight-vs-totango-vs-renewal360': typeof BlogGainsightVsTotangoVsRenewal360Route
  '/blog/how-renewal360-works': typeof BlogHowRenewal360WorksRoute
  '/blog/how-to-automate-saas-renewal-emails': typeof BlogHowToAutomateSaasRenewalEmailsRoute
  '/blog/how-to-run-your-entire-cs-operation-in-renewal360': typeof BlogHowToRunYourEntireCsOperationInRenewal360Route
  '/blog/totango-alternative-faster-renewal-automation': typeof BlogTotangoAlternativeFasterRenewalAutomationRoute
  '/blog/what-is-renewal-automation': typeof BlogWhatIsRenewalAutomationRoute
  '/blog/why-saas-companies-lose-renewals': typeof BlogWhySaasCompaniesLoseRenewalsRoute
  '/blog/zendesk-hubspot-salesforce-cs-platform-comparison': typeof BlogZendeskHubspotSalesforceCsPlatformComparisonRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/features'
    | '/glimpses'
    | '/how-it-works'
    | '/payment-success'
    | '/pricing'
    | '/set-password'
    | '/terms'
    | '/blog/churnzero-alternative-growing-saas-teams'
    | '/blog/customer-success-platform-for-growing-saas'
    | '/blog/gainsight-vs-totango-vs-renewal360'
    | '/blog/how-renewal360-works'
    | '/blog/how-to-automate-saas-renewal-emails'
    | '/blog/how-to-run-your-entire-cs-operation-in-renewal360'
    | '/blog/totango-alternative-faster-renewal-automation'
    | '/blog/what-is-renewal-automation'
    | '/blog/why-saas-companies-lose-renewals'
    | '/blog/zendesk-hubspot-salesforce-cs-platform-comparison'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/features'
    | '/glimpses'
    | '/how-it-works'
    | '/payment-success'
    | '/pricing'
    | '/set-password'
    | '/terms'
    | '/blog/churnzero-alternative-growing-saas-teams'
    | '/blog/customer-success-platform-for-growing-saas'
    | '/blog/gainsight-vs-totango-vs-renewal360'
    | '/blog/how-renewal360-works'
    | '/blog/how-to-automate-saas-renewal-emails'
    | '/blog/how-to-run-your-entire-cs-operation-in-renewal360'
    | '/blog/totango-alternative-faster-renewal-automation'
    | '/blog/what-is-renewal-automation'
    | '/blog/why-saas-companies-lose-renewals'
    | '/blog/zendesk-hubspot-salesforce-cs-platform-comparison'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/features'
    | '/glimpses'
    | '/how-it-works'
    | '/payment-success'
    | '/pricing'
    | '/set-password'
    | '/terms'
    | '/blog/churnzero-alternative-growing-saas-teams'
    | '/blog/customer-success-platform-for-growing-saas'
    | '/blog/gainsight-vs-totango-vs-renewal360'
    | '/blog/how-renewal360-works'
    | '/blog/how-to-automate-saas-renewal-emails'
    | '/blog/how-to-run-your-entire-cs-operation-in-renewal360'
    | '/blog/totango-alternative-faster-renewal-automation'
    | '/blog/what-is-renewal-automation'
    | '/blog/why-saas-companies-lose-renewals'
    | '/blog/zendesk-hubspot-salesforce-cs-platform-comparison'
    | '/blog_/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  GlimpsesRoute: typeof GlimpsesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  SetPasswordRoute: typeof SetPasswordRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glimpses': {
      id: '/glimpses'
      path: '/glimpses'
      fullPath: '/glimpses'
      preLoaderRoute: typeof GlimpsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/zendesk-hubspot-salesforce-cs-platform-comparison': {
      id: '/blog/zendesk-hubspot-salesforce-cs-platform-comparison'
      path: '/zendesk-hubspot-salesforce-cs-platform-comparison'
      fullPath: '/blog/zendesk-hubspot-salesforce-cs-platform-comparison'
      preLoaderRoute: typeof BlogZendeskHubspotSalesforceCsPlatformComparisonRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/why-saas-companies-lose-renewals': {
      id: '/blog/why-saas-companies-lose-renewals'
      path: '/why-saas-companies-lose-renewals'
      fullPath: '/blog/why-saas-companies-lose-renewals'
      preLoaderRoute: typeof BlogWhySaasCompaniesLoseRenewalsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/what-is-renewal-automation': {
      id: '/blog/what-is-renewal-automation'
      path: '/what-is-renewal-automation'
      fullPath: '/blog/what-is-renewal-automation'
      preLoaderRoute: typeof BlogWhatIsRenewalAutomationRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/totango-alternative-faster-renewal-automation': {
      id: '/blog/totango-alternative-faster-renewal-automation'
      path: '/totango-alternative-faster-renewal-automation'
      fullPath: '/blog/totango-alternative-faster-renewal-automation'
      preLoaderRoute: typeof BlogTotangoAlternativeFasterRenewalAutomationRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-to-run-your-entire-cs-operation-in-renewal360': {
      id: '/blog/how-to-run-your-entire-cs-operation-in-renewal360'
      path: '/how-to-run-your-entire-cs-operation-in-renewal360'
      fullPath: '/blog/how-to-run-your-entire-cs-operation-in-renewal360'
      preLoaderRoute: typeof BlogHowToRunYourEntireCsOperationInRenewal360RouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-to-automate-saas-renewal-emails': {
      id: '/blog/how-to-automate-saas-renewal-emails'
      path: '/how-to-automate-saas-renewal-emails'
      fullPath: '/blog/how-to-automate-saas-renewal-emails'
      preLoaderRoute: typeof BlogHowToAutomateSaasRenewalEmailsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-renewal360-works': {
      id: '/blog/how-renewal360-works'
      path: '/how-renewal360-works'
      fullPath: '/blog/how-renewal360-works'
      preLoaderRoute: typeof BlogHowRenewal360WorksRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/gainsight-vs-totango-vs-renewal360': {
      id: '/blog/gainsight-vs-totango-vs-renewal360'
      path: '/gainsight-vs-totango-vs-renewal360'
      fullPath: '/blog/gainsight-vs-totango-vs-renewal360'
      preLoaderRoute: typeof BlogGainsightVsTotangoVsRenewal360RouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/customer-success-platform-for-growing-saas': {
      id: '/blog/customer-success-platform-for-growing-saas'
      path: '/customer-success-platform-for-growing-saas'
      fullPath: '/blog/customer-success-platform-for-growing-saas'
      preLoaderRoute: typeof BlogCustomerSuccessPlatformForGrowingSaasRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/churnzero-alternative-growing-saas-teams': {
      id: '/blog/churnzero-alternative-growing-saas-teams'
      path: '/churnzero-alternative-growing-saas-teams'
      fullPath: '/blog/churnzero-alternative-growing-saas-teams'
      preLoaderRoute: typeof BlogChurnzeroAlternativeGrowingSaasTeamsRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogChurnzeroAlternativeGrowingSaasTeamsRoute: typeof BlogChurnzeroAlternativeGrowingSaasTeamsRoute
  BlogCustomerSuccessPlatformForGrowingSaasRoute: typeof BlogCustomerSuccessPlatformForGrowingSaasRoute
  BlogGainsightVsTotangoVsRenewal360Route: typeof BlogGainsightVsTotangoVsRenewal360Route
  BlogHowRenewal360WorksRoute: typeof BlogHowRenewal360WorksRoute
  BlogHowToAutomateSaasRenewalEmailsRoute: typeof BlogHowToAutomateSaasRenewalEmailsRoute
  BlogHowToRunYourEntireCsOperationInRenewal360Route: typeof BlogHowToRunYourEntireCsOperationInRenewal360Route
  BlogTotangoAlternativeFasterRenewalAutomationRoute: typeof BlogTotangoAlternativeFasterRenewalAutomationRoute
  BlogWhatIsRenewalAutomationRoute: typeof BlogWhatIsRenewalAutomationRoute
  BlogWhySaasCompaniesLoseRenewalsRoute: typeof BlogWhySaasCompaniesLoseRenewalsRoute
  BlogZendeskHubspotSalesforceCsPlatformComparisonRoute: typeof BlogZendeskHubspotSalesforceCsPlatformComparisonRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogChurnzeroAlternativeGrowingSaasTeamsRoute:
    BlogChurnzeroAlternativeGrowingSaasTeamsRoute,
  BlogCustomerSuccessPlatformForGrowingSaasRoute:
    BlogCustomerSuccessPlatformForGrowingSaasRoute,
  BlogGainsightVsTotangoVsRenewal360Route:
    BlogGainsightVsTotangoVsRenewal360Route,
  BlogHowRenewal360WorksRoute: BlogHowRenewal360WorksRoute,
  BlogHowToAutomateSaasRenewalEmailsRoute:
    BlogHowToAutomateSaasRenewalEmailsRoute,
  BlogHowToRunYourEntireCsOperationInRenewal360Route:
    BlogHowToRunYourEntireCsOperationInRenewal360Route,
  BlogTotangoAlternativeFasterRenewalAutomationRoute:
    BlogTotangoAlternativeFasterRenewalAutomationRoute,
  BlogWhatIsRenewalAutomationRoute: BlogWhatIsRenewalAutomationRoute,
  BlogWhySaasCompaniesLoseRenewalsRoute: BlogWhySaasCompaniesLoseRenewalsRoute,
  BlogZendeskHubspotSalesforceCsPlatformComparisonRoute:
    BlogZendeskHubspotSalesforceCsPlatformComparisonRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  GlimpsesRoute: GlimpsesRoute,
  HowItWorksRoute: HowItWorksRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  SetPasswordRoute: SetPasswordRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
